### PR TITLE
HTTPFile has 'content_type' property

### PR DESCRIPTION
**Pull request by benoitbryon**
Allows HTTPDownloadView to proxy Content-Type header.
Refs #116

### CODE REVIEW

**Comment by Natim** [comment]
Should we add a test for it?

**Comment by benoitbryon** [comment]
> Should we add a test for it?

Ahah, you are right :)
Done: implementation of "content_type" property makes the test pass (it fails without it).

**Comment by benoitbryon** [comment]
@Natim: is it ok for you?

**Comment by Natim** [comment]
I didn't answer yesterday but I did review it :+1:

**Pull request merged**
