### PR TITLE
Add django 2.0 and python 3.6 support

### PR DESCRIPTION
**Pull request by jmerkow**
depends on #142

### CODE REVIEW

**Comment by jmerkow** [comment]
@sliverc @Natim @benoitbryon

**Comment by jmerkow** [comment]
I don't understand your travis setup, so I modified it a bit, Im happy to fix, if you explain it.  As is, it setups an explicit matrix.

**Comment by jmerkow** [comment]
Failures are due to a travis bug?  python3.4 isn't downloading correctly on some jobs.

**Comment by Natim** [comment]
This is awesome thanks

**Comment by jmerkow** [comment]
@sliverc @benoitbryon how do we get this merged?

**Comment by Natim** [comment]
Superseeded by #147

**Pull request closed without merging**
